import { Injectable } from '@angular/core';
import {InMemoryDbService} from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const posts = [
      {id: 1, title: 'Chính phủ đề nghị lùi thời gian thông qua Luật Đặc khu', feature: 'https://i-vnexpress.vnecdn.net/2018/06/09/TT-Nguyen-Xuan-Phuc-trao-doi-v-9814-6042-1528501778.jpg', teaser: 'Trước những phản biện trái chiều, Chính phủ đã đề nghị Quốc hội lùi thời gian xem xét thông qua dự thảo Luật Đặc khu sang kỳ họp sau.', content: 'Chính phủ vừa thống nhất với Ủy ban Thường vụ Quốc hội việc trình Quốc hội xem xét lùi việc thông qua Dự án Luật Đơn vị hành chính - kinh tế đặc biệt (Luật Đặc khu) từ kỳ họp thứ 5 sang kỳ họp thứ 6 (Quốc hội khóa 14) để có thêm thời gian nghiên cứu, hoàn thiện. Theo thông báo gửi lúc 3h sáng, Chính phủ cho hay việc đề nghị lùi thông qua Luật Đặc khu được thực hiện sau khi tiếp thu các ý kiến tâm huyết, trách nhiệm của các đại biểu Quốc hội, các nhà khoa học, nhà kinh tế, chuyên gia, cử tri và nhân dân cả nước.'},
      {id: 2, title: 'Chuyện thành bại của các đặc khu kinh tế trên thế giới', feature: 'https://i-kinhdoanh.vnecdn.net/2018/06/08/shenzen-1-6043-1528462656.jpg', teaser: 'Dù mô hình đặc khu đã có hàng chục năm, các nước vẫn chưa tìm ra công thức thành công chung, và không ít đã thất bại. ', content: 'Thâm Quyến được coi là ví dụ tiêu biểu nhất về áp dụng thành công mô hình đặc khu kinh tế. Thành phố này có vị trí chiến lược tại Quảng Đông, nằm tại lưu vực sông Châu Giang, gần Hong Kong, Macau và là cửa ngõ vào Trung Quốc. Năm 1980, lãnh đạo Trung Quốc thời đó - Đặng Tiểu Bình chỉ định Thâm Quyến sẽ là đặc khu đầu tiên trong nhóm năm đặc khu kinh tế của nước này. Chính phủ Trung Quốc đã giảm hoặc xóa bỏ thuế nhập khẩu, khuyến khích đầu tư nước ngoài, thành lập doanh nghiệp tư nhân, áp dụng công nghệ và khoa học để thúc đẩy tăng trưởng kinh tế - kỹ thuật. Đặc khu sử dụng hệ thống quy định linh hoạt, nhằm giúp Trung Quốc phát triển theo hướng xuất khẩu. Đây được đánh giá là một trong những quyết định thử nghiệm kinh tế táo bạo nhất khi đó.'},
      {id: 3, title: 'Thế giới ngày 9/6: Kim Jong-un dự kiến đến Singapore vào ngày mai', feature: 'https://i-vnexpress.vnecdn.net/2018/06/09/skynews-kim-kim-jong-un-428858-7266-1343-1528499924_600x0.jpg', teaser: 'Kim Jong-un dự kiến đến Singapore vào ngày mai, sinh viên Moskva biểu tình phản đối khu cổ động World Cup.', content: 'Một nguồn tin tham gia lên kế hoạch cho chuyến đi cho biết lãnh đạo Triều Tiên Kim Jong-un dự kiến bay đến sân bay Changi của Singapore ngày 10/6 trước hội nghị thượng đỉnh với Tổng thống Mỹ Trump, theo Reuters. Cơ quan Hàng không Dân dụng Singapore chưa bình luận về thông tin này. Nhà Trắng xác nhận Trump sẽ rời hội nghị thượng đỉnh G7 ở Charlevoix, Quebec, Canada vào ngày 9/6 sau đó bay thẳng đến Singapore và dự kiến có mặt ở quốc đảo vào ngày 10/6.'},
      {id: 4, title: 'Ông Trần Văn Mẫn rút khỏi danh sách thi tuyển phó giám đốc sở ở Đà Nẵng', feature: 'https://i-vnexpress.vnecdn.net/2018/06/09/kham-nha1-1119-1528523294.jpg', teaser: 'Trong đơn xin rút, ông Trần Văn Mẫn (con trai cựu chủ tịch Đà Nẵng) trình bày do chuyện gia đình nên không có thời gian, tâm trí ôn thi.', content: 'Trưa 9/6, ông Võ Ngọc Đồng, Giám đốc Sở Nội vụ Đà Nẵng, cho biết ông Trần Văn Mẫn (Trưởng phòng Đấu thầu, thẩm định và giám sát đầu tư thuộc Sở Kế hoạch Đầu tư) đã có đơn xin rút không thi tuyển chức danh Phó giám đốc Sở Kế hoạch. "Cấp có thẩm quyền đã đồng ý cho anh Mẫn rút khỏi danh sách thi tuyển. Trong đơn, anh ấy trình bày do chuyện gia đình nên không có thời gian cũng như tâm trí tập trung ôn thi", ông Đồng nói và cho biết ông Mẫn đang chịu áp lực lớn từ dư luận trong thời gian qua. Hiện tại danh sách tham gia thi tuyển còn lại bốn người công tác tại Sở Kế hoạch Đầu tư Đà Nẵng, gồm: bà Nguyễn Thị Thu Nguyệt (Trưởng phòng Đăng ký kinh doanh), bà Lê Thị Kim Phượng (Trưởng phòng Kinh tế đối ngoại), ông Nguyễn Đình Tuấn (Trưởng phòng Doanh nghiệp, kinh tế tập thể và tư nhân) và ông Lê Thanh Tùng (Trưởng phòng Tổng hợp, quy hoạch).'},
      {id: 5, title: 'Đội cận vệ ưu tú có thể tháp tùng Kim Jong-un đến Singapore', feature: 'https://i-vnexpress.vnecdn.net/2018/06/09/34814368-2535365546489454-9115-7299-8927-1528520256.jpg', teaser: 'Chuyến đi Singapore của lãnh đạo Triều Tiên là thử thách mới cho nhóm cận vệ bởi đây là lần đầu tiên ông Kim tới quốc đảo sư tử.', content: 'Shawn Ho, một chuyên gia tại Trường Nghiên cứu Quốc tế S. Rajaratnam ở Singapore cho rằng, tháp tùng lãnh đạo Triều Tiên Kim Jong-un tới dự hội nghị thượng đỉnh với Tổng thống Mỹ Donald Trump là các cận vệ ưu tú và xe chống đạn, theo Straits Times. Tại hội nghị thượng đỉnh liên Triều hôm 27/4, những cận vệ cao to, vạm vỡ được nhìn thấy chạy theo chiếc limousine bọc thép của Kim. Họ phun phòng họp, đồ nội thất và cuốn sách Kim đã ký để khử trùng. Nhóm cận vệ cũng kiểm tra cẩn thận để phát hiện các thiết bị và vật liệu nổ.'}
    ];

    const categories = [
      {id: 1, name: 'Category 1', posts: [posts[0], posts[1]]},
      {id: 2, name: 'Category 2', posts: [posts[1], posts[2]]},
      {id: 3, name: 'Category 3', posts: [posts[2], posts[3]]},
      {id: 4, name: 'Category 4', posts: [posts[3], posts[4]]}
    ];

    return {categories, posts};
  }
}
